import type { Metadata } from "next";
import "./globals.css";
import { outfit, poppins } from "./fonts/font";


export const metadata: Metadata = {
  title: "Healixity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${outfit.variable} ${poppins.variable} antialiased `}
      >
        {children}
      </body>
      <script src="https://unpkg.com/lenis@1.1.20/dist/lenis.min.js" async />
    </html>
  );
}
