import type { Metadata } from "next";
import "./globals.css";
import { outfit, poppins } from "./fonts/font";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
  title: "Elephant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${outfit.variable} ${poppins.variable} antialiased overflow-x-hidden`}
      >
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster />
      </body>
      <script src="https://unpkg.com/lenis@1.1.20/dist/lenis.min.js" async />
    </html>
  );
}
